//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaExampleControllers
{
    [Serializable]
    public class RepulsiveFieldMsg : Message
    {
        public const string k_RosMessageName = "franka_example_controllers/RepulsiveField";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg centre;
        public double strength;
        public double active_radius;

        public RepulsiveFieldMsg()
        {
            this.centre = new Geometry.PointMsg();
            this.strength = 0.0;
            this.active_radius = 0.0;
        }

        public RepulsiveFieldMsg(Geometry.PointMsg centre, double strength, double active_radius)
        {
            this.centre = centre;
            this.strength = strength;
            this.active_radius = active_radius;
        }

        public static RepulsiveFieldMsg Deserialize(MessageDeserializer deserializer) => new RepulsiveFieldMsg(deserializer);

        private RepulsiveFieldMsg(MessageDeserializer deserializer)
        {
            this.centre = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.strength);
            deserializer.Read(out this.active_radius);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.centre);
            serializer.Write(this.strength);
            serializer.Write(this.active_radius);
        }

        public override string ToString()
        {
            return "RepulsiveFieldMsg: " +
            "\ncentre: " + centre.ToString() +
            "\nstrength: " + strength.ToString() +
            "\nactive_radius: " + active_radius.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
