//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaExampleControllers
{
    [Serializable]
    public class SafetyRepulsiveFieldsMsg : Message
    {
        public const string k_RosMessageName = "franka_example_controllers/SafetyRepulsiveFields";
        public override string RosMessageName => k_RosMessageName;

        public RepulsiveFieldMsg body;
        public RepulsiveFieldMsg left_hand;
        public RepulsiveFieldMsg right_hand;

        public SafetyRepulsiveFieldsMsg()
        {
            this.body = new RepulsiveFieldMsg();
            this.left_hand = new RepulsiveFieldMsg();
            this.right_hand = new RepulsiveFieldMsg();
        }

        public SafetyRepulsiveFieldsMsg(RepulsiveFieldMsg body, RepulsiveFieldMsg left_hand, RepulsiveFieldMsg right_hand)
        {
            this.body = body;
            this.left_hand = left_hand;
            this.right_hand = right_hand;
        }

        public static SafetyRepulsiveFieldsMsg Deserialize(MessageDeserializer deserializer) => new SafetyRepulsiveFieldsMsg(deserializer);

        private SafetyRepulsiveFieldsMsg(MessageDeserializer deserializer)
        {
            this.body = RepulsiveFieldMsg.Deserialize(deserializer);
            this.left_hand = RepulsiveFieldMsg.Deserialize(deserializer);
            this.right_hand = RepulsiveFieldMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.body);
            serializer.Write(this.left_hand);
            serializer.Write(this.right_hand);
        }

        public override string ToString()
        {
            return "SafetyRepulsiveFieldsMsg: " +
            "\nbody: " + body.ToString() +
            "\nleft_hand: " + left_hand.ToString() +
            "\nright_hand: " + right_hand.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
