//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaExampleControllers
{
    [Serializable]
    public class TargetPoseMsg : Message
    {
        public const string k_RosMessageName = "franka_example_controllers/TargetPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public double cartesian_stiffness;
        public double rotational_stiffness;

        public TargetPoseMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.cartesian_stiffness = 0.0;
            this.rotational_stiffness = 0.0;
        }

        public TargetPoseMsg(Geometry.PoseMsg pose, double cartesian_stiffness, double rotational_stiffness)
        {
            this.pose = pose;
            this.cartesian_stiffness = cartesian_stiffness;
            this.rotational_stiffness = rotational_stiffness;
        }

        public static TargetPoseMsg Deserialize(MessageDeserializer deserializer) => new TargetPoseMsg(deserializer);

        private TargetPoseMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.cartesian_stiffness);
            deserializer.Read(out this.rotational_stiffness);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.cartesian_stiffness);
            serializer.Write(this.rotational_stiffness);
        }

        public override string ToString()
        {
            return "TargetPoseMsg: " +
            "\npose: " + pose.ToString() +
            "\ncartesian_stiffness: " + cartesian_stiffness.ToString() +
            "\nrotational_stiffness: " + rotational_stiffness.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
